project:
  type: website
  output-dir: _docs
  render:
    - "*.qmd"
    - "*.md"

website:
  title: "watanabe3ti.github.io"
  navbar:
    aria-label: Main navigation
    background: dark
    search: true
    left:
      - href: index.qmd
        text: Home
      - text: Contents
        menu:
          - href: content1.qmd
            text: Content1
          - href: content2.qmd
            text: Content2
          - href: content3.qmd
            text: Content3
      - text: Links
        href: links.qmd
    right:
      - href: about.qmd  
        text: About
      - href: "https://github.com/watanabe3ti/watanabe3ti.github.io"
        text: GitHub(.&-)
      - href: "https://watanabe3tipapa.github.io"
        icon: github
  page-footer:
    background: dark
    center: Copyright 2024, watanabe3tipapa
format:
  html:
    theme: spacelab
    css: styles.css
    toc: true

editor: visual

